[31mERROR[39m: error al conectar a DB: bad auth : authentication failed
